spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate 사용
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

logging:
  level:
    org.hibernate.type: info # 콘솔창에 조건에 바인딩되는 값 및 조회결과 출